wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    session_history: code/_session_history.ipynb
    start_time: 1674233549.434992
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      2:
      - 2
      - 3
      - 12
      - 55
      3:
      - 2
      - 23
      4: 3.9.7
      5: 0.13.9
      8:
      - 1
      - 4
      - 5
